version: '3'
services:
  #ADONIS APP
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - ${APP_PORT}:3333
    volumes:
      - ./server:/app
    working_dir: /app
    networks:
      - app-network
  #DATABASE
  mysql:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    container_name: mysql_sbhc
    restart: on-failure
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata: {}
